language: rust
cache: cargo

env:
  global:
  - CARGO_FLAGS=""
  - TARGET_OUT=release

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

  include:
  - rust: stable
    os: linux
    env: TARGET=x86_64-unknown-linux-musl CARGO_FLAGS=--target=x86_64-unknown-linux-musl TARGET_OUT=x86_64-unknown-linux-musl/release
  - rust: stable
    os: osx
  - rust: beta
    os: linux
  - rust: nightly
    os: linux

before_install:
- 'if [[ ${TARGET} = x86_64-unknown-linux-musl ]]; then sudo apt-get install -y musl-tools; fi'

install:
- 'if [[ -n ${TARGET} ]]; then rustup target add ${TARGET}; fi'

script:
- 'echo Using rust ${TRAVIS_RUST_VERSION} ${TARGET}'
- 'cargo test ${CARGO_FLAGS} --release --verbose'
- 'pushd cli; cargo test ${CARGO_FLAGS} --release --verbose; popd'

before_deploy:
- 'pushd cli; cargo build ${CARGO_FLAGS} --release --verbose; popd'
- 'if [[ ${TRAVIS_OS_NAME} = linux ]]; then strip target/${TARGET_OUT}/askalono; fi'
- 'stat target/${TARGET_OUT}/askalono'
- 'mv target/${TARGET_OUT}/askalono target/askalono.${TRAVIS_OS_NAME}'
deploy:
  provider: releases
  api_key: '${TRAVIS_GITHUB_RELEASES_TOKEN}' # configured in repo settings online
  file: target/askalono.*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    condition: '${TRAVIS_RUST_VERSION} = stable'
