[package]
name = "askalono"
version = "0.2.0"
description = "a library to detect the contents of license files"
license = "Apache-2.0"
repository = "https://github.com/amzn/askalono"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]
readme = "README.md"
exclude = [
    "/license-list-data/**/*"
]

[dependencies]
failure = "0.1.1"
flate2 = "1.0.1"
lazy_static = "1.0.0"
log = "0.4.1"
rayon = "1.0.1"
regex = "0.2.10"
rmp-serde = "0.13.7"
serde = "1.0.33"
serde_derive = "1.0.33"
unicode-normalization = "0.1.5"

# spdx deps
serde_json = { version = "1.0.11", optional = true }
walkdir = { version = "2.1.4", optional = true }

[workspace]
members = ["cli"]

[lib]
name = "askalono"
path = "src/lib.rs"

[features]
default = ["spdx"]
spdx = ["serde_json", "walkdir"]
