[package]
name = "askalono-cli"
version = "0.3.0"
edition = "2018"
description = "a tool to detect the contents of license files"
license = "Apache-2.0"
repository = "https://github.com/amzn/askalono"
authors = ["Jacob Peddicord <peddicor@amazon.com>"]
readme = "../README.md"
include = [
    "/src/**/*",
    "/build.rs",
    "/Cargo.*",
    "/embedded-cache.bin.gz",
]

[dependencies]
askalono = { version = "0.3.0", path = "../" }
clap = "2.20"
env_logger = "0.5.5"
failure = "0.1.1"
ignore = "0.4.1"
log = "0.4.1"
rayon = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2.5"

difference = { version = "2.0.0", optional = true }

[build-dependencies]
askalono = { version = "0.3.0", path = "../" }

[[bin]]
name = "askalono"
path = "src/main.rs"

[features]
default = ["embedded-cache"]
diagnostics = ["difference"]
embedded-cache = []
