[package]
name = "lambda"
version = "0.1.0"
authors = ["Jacob Peddicord <jacob@peddicord.net>"]
edition = "2018"

[dependencies]
askalono = { version = "0.4", path = "../../" }
lambda_http = "0.1"
lambda_runtime = "0.2"
lazy_static = "1.4"
